### ISSUE TITLE
Omnifocus compatibility

### ISSUE THREAD

**Issue by ramm** [nfarina/dropdav#1]
Unable to perform WebDAV operation.

The dropdav.appspot.com server returned “internal server error” (500) in response to a request to “PROPFIND /OmniFocus.ofocus”

When i try to sync my OmniFocus with dropdav at dropdav.appspot.com

**Comment by neilpie** [comment]
I have just successfully set up iPhone/iMac/MBP Omnifocus syncing via DropDAV. It appears to be working perfectly

**Comment by ramm** [comment]
Hmmm, but how?
http://dl.dropbox.com/u/510896/_screenshot/2011-01-24_1352.png

**Comment by ramm** [comment]
Ah, i see now. You should first sync it to "Disk" in fropbox folder, then it works like a charm.
